/***********************************************************************************************************************
* DISCLAIMER
* This software is supplied by Renesas Electronics Corporation and is only 
* intended for use with Renesas products. No other uses are authorized. This 
* software is owned by Renesas Electronics Corporation and is protected under 
* all applicable laws, including copyright laws.
* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING 
* THIS SOFTWARE, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT 
* LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE 
* AND NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.
* TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY LAW, NEITHER RENESAS 
* ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE 
* FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR 
* ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR ITS AFFILIATES HAVE 
* BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
* Renesas reserves the right, without notice, to make changes to this software 
* and to discontinue the availability of this software.  By using this software, 
* you agree to the additional terms and conditions found by accessing the 
* following link:
* http://www.renesas.com/disclaimer
*
* Copyright (C) 2015, 2018 Renesas Electronics Corporation. All rights reserved.
***********************************************************************************************************************/

/***********************************************************************************************************************
* File Name    : r_cg_port.c
* Version      : Code Generator for RH850/F1K V1.01.02.02 [08 May 2018]
* Device(s)    : R7F701623(LQFP144pin)
* Tool-Chain   : CCRH
* Description  : This file implements device driver for Port module.
* Creation Date: 07-06-2023
***********************************************************************************************************************/

/***********************************************************************************************************************
Pragma directive
***********************************************************************************************************************/
/* Start user code for pragma. Do not edit comment generated here */
/* End user code. Do not edit comment generated here */

/***********************************************************************************************************************
Includes
***********************************************************************************************************************/
#include "r_cg_macrodriver.h"
#include "r_cg_port.h"
/* Start user code for include. Do not edit comment generated here */
/* End user code. Do not edit comment generated here */
#include "r_cg_userdefine.h"

/***********************************************************************************************************************
Global variables and functions
***********************************************************************************************************************/
extern volatile uint32_t g_cg_sync_read      /* Synchronization processing */;
/* Start user code for global. Do not edit comment generated here */
/* End user code. Do not edit comment generated here */

/***********************************************************************************************************************
* Function Name: R_PORT_Create
* Description  : This function initializes the Port I/O.
* Arguments    : None
* Return Value : None
***********************************************************************************************************************/
void R_PORT_Create(void)
{
    /* PORT initialization */
    PORT.PIBC0 = _PORT_PIBC_INIT;
    PORT.PIBC1 = _PORT_PIBC_INIT;
    PORT.PIBC8 = _PORT_PIBC_INIT;
    PORT.PIBC9 = _PORT_PIBC_INIT;
    PORT.PIBC10 = _PORT_PIBC_INIT;
    PORT.PIBC11 = _PORT_PIBC_INIT;
    PORT.PIBC18 = _PORT_PIBC_INIT;
    PORT.PIBC20 = _PORT_PIBC_INIT;
    PORT.PBDC0 = _PORT_PBDC_INIT;
    PORT.PBDC1 = _PORT_PBDC_INIT;
    PORT.PBDC8 = _PORT_PBDC_INIT;
    PORT.PBDC9 = _PORT_PBDC_INIT;
    PORT.PBDC10 = _PORT_PBDC_INIT;
    PORT.PBDC11 = _PORT_PBDC_INIT;
    PORT.PM0 = _PORT_PM_INIT;
    PORT.PM1 = _PORT_PM_INIT;
    PORT.PM8 = _PORT_PM_INIT;
    PORT.PM9 = _PORT_PM_INIT;
    PORT.PM10 = _PORT_PM_INIT;
    PORT.PM11 = _PORT_PM_INIT;
    PORT.PMC0 = _PORT_PMC_INIT;
    PORT.PMC1 = _PORT_PMC_INIT;
    PORT.PMC8 = _PORT_PMC_INIT;
    PORT.PMC9 = _PORT_PMC_INIT;
    PORT.PMC10 = _PORT_PMC_INIT;
    PORT.PMC11 = _PORT_PMC_INIT;
    PORT.PIPC0= _PORT_PIPC_INIT;
    PORT.PIPC10= _PORT_PIPC_INIT;
    PORT.PIPC11= _PORT_PIPC_INIT;
    /* Port0 setting */
    PORT.PPCMD0 = _WRITE_PROTECT_COMMAND;
    PORT.PDSC0 = _PORT_PDSCn10_FAST_MODE_SELECT | _PORT_PDSCn6_SLOW_MODE_SELECT;
    PORT.PDSC0 = (uint32_t) ~(_PORT_PDSCn10_FAST_MODE_SELECT | _PORT_PDSCn6_SLOW_MODE_SELECT);
    PORT.PDSC0 = _PORT_PDSCn10_FAST_MODE_SELECT | _PORT_PDSCn6_SLOW_MODE_SELECT;
    PORT.PPCMD0 = _WRITE_PROTECT_COMMAND;
    PORT.PODC0 = _PORT_PODCn10_PUSH_PULL | _PORT_PODCn6_PUSH_PULL;
    PORT.PODC0 = (uint32_t) ~(_PORT_PODCn10_PUSH_PULL | _PORT_PODCn6_PUSH_PULL);
    PORT.PODC0 = _PORT_PODCn10_PUSH_PULL | _PORT_PODCn6_PUSH_PULL;
    PORT.PBDC0 = _PORT_PBDCn10_PBDC_MODE_DISABLED | _PORT_PBDCn6_PBDC_MODE_DISABLED;
    PORT.PU0 = _PORT_PUn14_PULLUP_OFF | _PORT_PUn13_PULLUP_OFF | _PORT_PUn11_PULLUP_OFF | _PORT_PUn9_PULLUP_OFF | 
               _PORT_PUn7_PULLUP_OFF | _PORT_PUn5_PULLUP_OFF | _PORT_PUn4_PULLUP_OFF | _PORT_PUn3_PULLUP_OFF | 
               _PORT_PUn2_PULLUP_OFF | _PORT_PUn1_PULLUP_OFF | _PORT_PUn0_PULLUP_OFF;
    PORT.PD0 = _PORT_PDn12_PULLDOWN_ON | _PORT_PDn11_PULLDOWN_OFF | _PORT_PDn9_PULLDOWN_OFF | _PORT_PDn8_PULLDOWN_ON | 
               _PORT_PDn7_PULLDOWN_OFF | _PORT_PDn5_PULLDOWN_OFF | _PORT_PDn4_PULLDOWN_OFF | _PORT_PDn3_PULLDOWN_OFF | 
               _PORT_PDn2_PULLDOWN_OFF | _PORT_PDn1_PULLDOWN_OFF | _PORT_PDn0_PULLDOWN_OFF;
    PORT.P0 = _PORT_Pn10_OUTPUT_LOW | _PORT_Pn6_OUTPUT_LOW;
    PORT.PM0 = _PORT_PM0_DEFAULT_VALUE | _PORT_PMn14_MODE_UNUSED | _PORT_PMn13_MODE_UNUSED | _PORT_PMn12_MODE_UNUSED | 
               _PORT_PMn11_MODE_UNUSED | _PORT_PMn10_MODE_OUTPUT | _PORT_PMn9_MODE_UNUSED | _PORT_PMn8_MODE_UNUSED | 
               _PORT_PMn7_MODE_UNUSED | _PORT_PMn6_MODE_OUTPUT | _PORT_PMn5_MODE_UNUSED | _PORT_PMn4_MODE_UNUSED | 
               _PORT_PMn3_MODE_UNUSED | _PORT_PMn2_MODE_UNUSED | _PORT_PMn1_MODE_UNUSED | _PORT_PMn0_MODE_UNUSED;
    /* Port1 setting */
    PORT.PPCMD1 = _WRITE_PROTECT_COMMAND;
    PORT.PDSC1 = _PORT_PDSCn5_SLOW_MODE_SELECT | _PORT_PDSCn3_SLOW_MODE_SELECT | _PORT_PDSCn2_SLOW_MODE_SELECT | 
                 _PORT_PDSCn1_SLOW_MODE_SELECT;
    PORT.PDSC1 = (uint32_t) ~(_PORT_PDSCn5_SLOW_MODE_SELECT | _PORT_PDSCn3_SLOW_MODE_SELECT | 
                 _PORT_PDSCn2_SLOW_MODE_SELECT | _PORT_PDSCn1_SLOW_MODE_SELECT);
    PORT.PDSC1 = _PORT_PDSCn5_SLOW_MODE_SELECT | _PORT_PDSCn3_SLOW_MODE_SELECT | _PORT_PDSCn2_SLOW_MODE_SELECT | 
                 _PORT_PDSCn1_SLOW_MODE_SELECT;
    PORT.PPCMD1 = _WRITE_PROTECT_COMMAND;
    PORT.PODC1 = _PORT_PODCn5_PUSH_PULL | _PORT_PODCn3_PUSH_PULL | _PORT_PODCn2_PUSH_PULL | _PORT_PODCn1_PUSH_PULL;
    PORT.PODC1 = (uint32_t) ~(_PORT_PODCn5_PUSH_PULL | _PORT_PODCn3_PUSH_PULL | _PORT_PODCn2_PUSH_PULL | 
                 _PORT_PODCn1_PUSH_PULL);
    PORT.PODC1 = _PORT_PODCn5_PUSH_PULL | _PORT_PODCn3_PUSH_PULL | _PORT_PODCn2_PUSH_PULL | _PORT_PODCn1_PUSH_PULL;
    PORT.PBDC1 = _PORT_PBDCn5_PBDC_MODE_DISABLED | _PORT_PBDCn3_PBDC_MODE_DISABLED | _PORT_PBDCn2_PBDC_MODE_DISABLED | 
                 _PORT_PBDCn1_PBDC_MODE_DISABLED;
    PORT.PU1 = _PORT_PUn11_PULLUP_OFF | _PORT_PUn10_PULLUP_OFF | _PORT_PUn9_PULLUP_OFF | _PORT_PUn8_PULLUP_OFF | 
               _PORT_PUn7_PULLUP_OFF | _PORT_PUn6_PULLUP_OFF | _PORT_PUn4_PULLUP_OFF | _PORT_PUn0_PULLUP_OFF;
    PORT.PD1 = _PORT_PDn11_PULLDOWN_OFF | _PORT_PDn10_PULLDOWN_OFF | _PORT_PDn9_PULLDOWN_OFF | 
               _PORT_PDn8_PULLDOWN_OFF | _PORT_PDn7_PULLDOWN_OFF | _PORT_PDn6_PULLDOWN_OFF | _PORT_PDn4_PULLDOWN_OFF | 
               _PORT_PDn0_PULLDOWN_OFF;
    PORT.PIS1 = _PORT_PIS1_DEFAULT_VALUE | _PORT_PISn11_TYPE_SHMT4 | _PORT_PISn10_TYPE_SHMT4 | 
                _PORT_PISn9_TYPE_SHMT4 | _PORT_PISn8_TYPE_SHMT4 | _PORT_PISn7_TYPE_SHMT4 | _PORT_PISn6_TYPE_SHMT4 | 
                _PORT_PISn4_TYPE_SHMT4 | _PORT_PISn0_TYPE_SHMT4;
    PORT.P1 = _PORT_Pn5_OUTPUT_LOW | _PORT_Pn3_OUTPUT_LOW | _PORT_Pn2_OUTPUT_LOW | _PORT_Pn1_OUTPUT_LOW;
    PORT.PM1 = _PORT_PM1_DEFAULT_VALUE | _PORT_PMn11_MODE_UNUSED | _PORT_PMn10_MODE_UNUSED | _PORT_PMn9_MODE_INPUT | 
               _PORT_PMn8_MODE_UNUSED | _PORT_PMn7_MODE_UNUSED | _PORT_PMn6_MODE_INPUT | _PORT_PMn5_MODE_OUTPUT | 
               _PORT_PMn4_MODE_UNUSED | _PORT_PMn3_MODE_OUTPUT | _PORT_PMn2_MODE_OUTPUT | _PORT_PMn1_MODE_OUTPUT | 
               _PORT_PMn0_MODE_UNUSED;
    PORT.PIBC1 = _PORT_PIBCn9_INPUT_BUFFER_ENABLE | _PORT_PIBCn6_INPUT_BUFFER_ENABLE;
    /* Port8 setting */
    PORT.PPCMD8 = _WRITE_PROTECT_COMMAND;
    PORT.PODC8 = _PORT_PODCn11_PUSH_PULL | _PORT_PODCn10_PUSH_PULL | _PORT_PODCn1_PUSH_PULL;
    PORT.PODC8 = (uint32_t) ~(_PORT_PODCn11_PUSH_PULL | _PORT_PODCn10_PUSH_PULL | _PORT_PODCn1_PUSH_PULL);
    PORT.PODC8 = _PORT_PODCn11_PUSH_PULL | _PORT_PODCn10_PUSH_PULL | _PORT_PODCn1_PUSH_PULL;
    PORT.PBDC8 = _PORT_PBDCn11_PBDC_MODE_DISABLED | _PORT_PBDCn10_PBDC_MODE_DISABLED | _PORT_PBDCn1_PBDC_MODE_DISABLED;
    PORT.PU8 = _PORT_PUn12_PULLUP_OFF | _PORT_PUn9_PULLUP_OFF | _PORT_PUn8_PULLUP_OFF | _PORT_PUn7_PULLUP_OFF | 
               _PORT_PUn6_PULLUP_OFF | _PORT_PUn5_PULLUP_ON | _PORT_PUn4_PULLUP_OFF | _PORT_PUn3_PULLUP_OFF | 
               _PORT_PUn2_PULLUP_OFF | _PORT_PUn0_PULLUP_OFF;
    PORT.PD8 = _PORT_PDn12_PULLDOWN_OFF | _PORT_PDn9_PULLDOWN_OFF | _PORT_PDn8_PULLDOWN_OFF | 
               _PORT_PDn7_PULLDOWN_OFF | _PORT_PDn6_PULLDOWN_OFF | _PORT_PDn4_PULLDOWN_OFF | _PORT_PDn3_PULLDOWN_OFF | 
               _PORT_PDn2_PULLDOWN_OFF | _PORT_PDn0_PULLDOWN_OFF;
    PORT.PIS8 = _PORT_PIS8_DEFAULT_VALUE | _PORT_PISn12_TYPE_SHMT4 | _PORT_PISn9_TYPE_SHMT4 | _PORT_PISn8_TYPE_SHMT4 | 
                _PORT_PISn7_TYPE_SHMT4 | _PORT_PISn6_TYPE_SHMT4 | _PORT_PISn5_TYPE_SHMT4 | _PORT_PISn4_TYPE_SHMT4 | 
                _PORT_PISn3_TYPE_SHMT4 | _PORT_PISn2_TYPE_SHMT4 | _PORT_PISn0_TYPE_SHMT4;
    PORT.P8 = _PORT_Pn11_OUTPUT_HIGH | _PORT_Pn10_OUTPUT_LOW | _PORT_Pn1_OUTPUT_LOW;
    PORT.PM8 = _PORT_PM8_DEFAULT_VALUE | _PORT_PMn12_MODE_UNUSED | _PORT_PMn11_MODE_OUTPUT | _PORT_PMn10_MODE_OUTPUT | 
               _PORT_PMn9_MODE_INPUT | _PORT_PMn8_MODE_INPUT | _PORT_PMn7_MODE_UNUSED | _PORT_PMn6_MODE_UNUSED | 
               _PORT_PMn5_MODE_UNUSED | _PORT_PMn4_MODE_UNUSED | _PORT_PMn3_MODE_UNUSED | _PORT_PMn2_MODE_UNUSED | 
               _PORT_PMn1_MODE_OUTPUT | _PORT_PMn0_MODE_UNUSED;
    PORT.PIBC8 = _PORT_PIBCn9_INPUT_BUFFER_ENABLE | _PORT_PIBCn8_INPUT_BUFFER_ENABLE;
    /* Port9 setting */
    PORT.PU9 = _PORT_PUn6_PULLUP_OFF | _PORT_PUn5_PULLUP_OFF | _PORT_PUn4_PULLUP_OFF | _PORT_PUn3_PULLUP_OFF | 
               _PORT_PUn2_PULLUP_OFF | _PORT_PUn1_PULLUP_OFF | _PORT_PUn0_PULLUP_OFF;
    PORT.PD9 = _PORT_PDn6_PULLDOWN_OFF | _PORT_PDn5_PULLDOWN_OFF | _PORT_PDn4_PULLDOWN_OFF | _PORT_PDn3_PULLDOWN_OFF | 
               _PORT_PDn2_PULLDOWN_OFF | _PORT_PDn1_PULLDOWN_OFF | _PORT_PDn0_PULLDOWN_OFF;
    PORT.PIS9 = _PORT_PIS9_DEFAULT_VALUE | _PORT_PISn6_TYPE_SHMT4 | _PORT_PISn5_TYPE_SHMT4 | _PORT_PISn4_TYPE_SHMT4 | 
                _PORT_PISn3_TYPE_SHMT4 | _PORT_PISn2_TYPE_SHMT4 | _PORT_PISn1_TYPE_SHMT4 | _PORT_PISn0_TYPE_SHMT4;
    PORT.PM9 = _PORT_PM9_DEFAULT_VALUE | _PORT_PMn6_MODE_UNUSED | _PORT_PMn5_MODE_INPUT | _PORT_PMn4_MODE_INPUT | 
               _PORT_PMn3_MODE_INPUT | _PORT_PMn2_MODE_INPUT | _PORT_PMn1_MODE_INPUT | _PORT_PMn0_MODE_INPUT;
    PORT.PIBC9 = _PORT_PIBCn5_INPUT_BUFFER_ENABLE | _PORT_PIBCn4_INPUT_BUFFER_ENABLE | 
                 _PORT_PIBCn3_INPUT_BUFFER_ENABLE | _PORT_PIBCn2_INPUT_BUFFER_ENABLE | 
                 _PORT_PIBCn1_INPUT_BUFFER_ENABLE | _PORT_PIBCn0_INPUT_BUFFER_ENABLE;
    /* Port10 setting */
    PORT.PPCMD10 = _WRITE_PROTECT_COMMAND;
    PORT.PDSC10 = _PORT_PDSCn15_SLOW_MODE_SELECT | _PORT_PDSCn8_SLOW_MODE_SELECT;
    PORT.PDSC10 = (uint32_t) ~(_PORT_PDSCn15_SLOW_MODE_SELECT | _PORT_PDSCn8_SLOW_MODE_SELECT);
    PORT.PDSC10 = _PORT_PDSCn15_SLOW_MODE_SELECT | _PORT_PDSCn8_SLOW_MODE_SELECT;
    PORT.PPCMD10 = _WRITE_PROTECT_COMMAND;
    PORT.PODC10 = _PORT_PODCn15_PUSH_PULL | _PORT_PODCn8_PUSH_PULL;
    PORT.PODC10 = (uint32_t) ~(_PORT_PODCn15_PUSH_PULL | _PORT_PODCn8_PUSH_PULL);
    PORT.PODC10 = _PORT_PODCn15_PUSH_PULL | _PORT_PODCn8_PUSH_PULL;
    PORT.PBDC10 = _PORT_PBDCn15_PBDC_MODE_DISABLED | _PORT_PBDCn8_PBDC_MODE_DISABLED;
    PORT.PU10 = _PORT_PUn14_PULLUP_OFF | _PORT_PUn13_PULLUP_OFF | _PORT_PUn12_PULLUP_ON | _PORT_PUn11_PULLUP_OFF | 
                _PORT_PUn10_PULLUP_OFF | _PORT_PUn9_PULLUP_OFF | _PORT_PUn7_PULLUP_ON | _PORT_PUn6_PULLUP_OFF | 
                _PORT_PUn5_PULLUP_OFF | _PORT_PUn4_PULLUP_OFF | _PORT_PUn3_PULLUP_OFF | _PORT_PUn2_PULLUP_OFF | 
                _PORT_PUn1_PULLUP_OFF | _PORT_PUn0_PULLUP_OFF;
    PORT.PD10 = _PORT_PDn14_PULLDOWN_OFF | _PORT_PDn13_PULLDOWN_OFF | _PORT_PDn11_PULLDOWN_OFF | 
                _PORT_PDn10_PULLDOWN_OFF | _PORT_PDn9_PULLDOWN_OFF | _PORT_PDn6_PULLDOWN_OFF | 
                _PORT_PDn5_PULLDOWN_OFF | _PORT_PDn4_PULLDOWN_OFF | _PORT_PDn3_PULLDOWN_OFF | 
                _PORT_PDn2_PULLDOWN_OFF | _PORT_PDn1_PULLDOWN_OFF | _PORT_PDn0_PULLDOWN_OFF;
    PORT.PIS10 = _PORT_PISn14_TYPE_SHMT4 | _PORT_PISn13_TYPE_SHMT4 | _PORT_PISn12_TYPE_SHMT4 | 
                 _PORT_PISn11_TYPE_SHMT4 | _PORT_PISn10_TYPE_SHMT4 | _PORT_PISn9_TYPE_SHMT4 | _PORT_PISn7_TYPE_SHMT4 | 
                 _PORT_PISn6_TYPE_SHMT4 | _PORT_PISn5_TYPE_SHMT4 | _PORT_PISn4_TYPE_SHMT4 | _PORT_PISn3_TYPE_SHMT1 | 
                 _PORT_PISn2_TYPE_SHMT4 | _PORT_PISn1_TYPE_SHMT4 | _PORT_PISn0_TYPE_SHMT4;
    PORT.P10 = _PORT_Pn15_OUTPUT_LOW | _PORT_Pn8_OUTPUT_LOW;
    PORT.PM10 = _PORT_PMn15_MODE_OUTPUT | _PORT_PMn14_MODE_UNUSED | _PORT_PMn13_MODE_INPUT | _PORT_PMn12_MODE_INPUT | 
                _PORT_PMn11_MODE_UNUSED | _PORT_PMn10_MODE_UNUSED | _PORT_PMn9_MODE_UNUSED | _PORT_PMn8_MODE_OUTPUT | 
                _PORT_PMn7_MODE_UNUSED | _PORT_PMn6_MODE_UNUSED | _PORT_PMn5_MODE_UNUSED | _PORT_PMn4_MODE_UNUSED | 
                _PORT_PMn3_MODE_UNUSED | _PORT_PMn2_MODE_UNUSED | _PORT_PMn1_MODE_UNUSED | _PORT_PMn0_MODE_UNUSED;
    PORT.PIBC10 = _PORT_PIBCn13_INPUT_BUFFER_ENABLE | _PORT_PIBCn12_INPUT_BUFFER_ENABLE;
    /* Port11 setting */
    PORT.PPCMD11 = _WRITE_PROTECT_COMMAND;
    PORT.PDSC11 = _PORT_PDSCn14_SLOW_MODE_SELECT | _PORT_PDSCn13_SLOW_MODE_SELECT | _PORT_PDSCn12_SLOW_MODE_SELECT | 
                  _PORT_PDSCn11_SLOW_MODE_SELECT | _PORT_PDSCn10_SLOW_MODE_SELECT | _PORT_PDSCn9_SLOW_MODE_SELECT;
    PORT.PDSC11 = (uint32_t) ~(_PORT_PDSCn14_SLOW_MODE_SELECT | _PORT_PDSCn13_SLOW_MODE_SELECT | 
                  _PORT_PDSCn12_SLOW_MODE_SELECT | _PORT_PDSCn11_SLOW_MODE_SELECT | _PORT_PDSCn10_SLOW_MODE_SELECT | 
                  _PORT_PDSCn9_SLOW_MODE_SELECT);
    PORT.PDSC11 = _PORT_PDSCn14_SLOW_MODE_SELECT | _PORT_PDSCn13_SLOW_MODE_SELECT | _PORT_PDSCn12_SLOW_MODE_SELECT | 
                  _PORT_PDSCn11_SLOW_MODE_SELECT | _PORT_PDSCn10_SLOW_MODE_SELECT | _PORT_PDSCn9_SLOW_MODE_SELECT;
    PORT.PPCMD11 = _WRITE_PROTECT_COMMAND;
    PORT.PODC11 = _PORT_PODCn14_PUSH_PULL | _PORT_PODCn13_PUSH_PULL | _PORT_PODCn12_PUSH_PULL | 
                  _PORT_PODCn11_PUSH_PULL | _PORT_PODCn10_PUSH_PULL | _PORT_PODCn9_PUSH_PULL;
    PORT.PODC11 = (uint32_t) ~(_PORT_PODCn14_PUSH_PULL | _PORT_PODCn13_PUSH_PULL | _PORT_PODCn12_PUSH_PULL | 
                  _PORT_PODCn11_PUSH_PULL | _PORT_PODCn10_PUSH_PULL | _PORT_PODCn9_PUSH_PULL);
    PORT.PODC11 = _PORT_PODCn14_PUSH_PULL | _PORT_PODCn13_PUSH_PULL | _PORT_PODCn12_PUSH_PULL | 
                  _PORT_PODCn11_PUSH_PULL | _PORT_PODCn10_PUSH_PULL | _PORT_PODCn9_PUSH_PULL;
    PORT.PBDC11 = _PORT_PBDCn14_PBDC_MODE_DISABLED | _PORT_PBDCn13_PBDC_MODE_DISABLED | 
                  _PORT_PBDCn12_PBDC_MODE_DISABLED | _PORT_PBDCn11_PBDC_MODE_DISABLED | 
                  _PORT_PBDCn10_PBDC_MODE_DISABLED | _PORT_PBDCn9_PBDC_MODE_DISABLED;
    PORT.PU11 = _PORT_PUn15_PULLUP_OFF | _PORT_PUn7_PULLUP_OFF | _PORT_PUn6_PULLUP_OFF | _PORT_PUn5_PULLUP_OFF | 
                _PORT_PUn4_PULLUP_OFF | _PORT_PUn3_PULLUP_OFF | _PORT_PUn2_PULLUP_OFF | _PORT_PUn1_PULLUP_OFF | 
                _PORT_PUn0_PULLUP_OFF;
    PORT.PD11 = _PORT_PDn15_PULLDOWN_OFF | _PORT_PDn8_PULLDOWN_ON | _PORT_PDn7_PULLDOWN_OFF | 
                _PORT_PDn6_PULLDOWN_OFF | _PORT_PDn5_PULLDOWN_OFF | _PORT_PDn4_PULLDOWN_OFF | 
                _PORT_PDn3_PULLDOWN_OFF | _PORT_PDn2_PULLDOWN_OFF | _PORT_PDn1_PULLDOWN_OFF | _PORT_PDn0_PULLDOWN_OFF;
    PORT.PIS11 = _PORT_PISn15_TYPE_SHMT4 | _PORT_PISn8_TYPE_SHMT4 | _PORT_PISn7_TYPE_SHMT4 | _PORT_PISn6_TYPE_SHMT4 | 
                 _PORT_PISn5_TYPE_SHMT4 | _PORT_PISn4_TYPE_SHMT4 | _PORT_PISn3_TYPE_SHMT4 | _PORT_PISn2_TYPE_SHMT4 | 
                 _PORT_PISn1_TYPE_SHMT4 | _PORT_PISn0_TYPE_SHMT4;
    PORT.P11 = _PORT_Pn14_OUTPUT_LOW | _PORT_Pn13_OUTPUT_LOW | _PORT_Pn12_OUTPUT_LOW | _PORT_Pn11_OUTPUT_HIGH | 
               _PORT_Pn10_OUTPUT_LOW | _PORT_Pn9_OUTPUT_LOW;
    PORT.PM11 = _PORT_PMn15_MODE_UNUSED | _PORT_PMn14_MODE_OUTPUT | _PORT_PMn13_MODE_OUTPUT | 
                _PORT_PMn12_MODE_OUTPUT | _PORT_PMn11_MODE_OUTPUT | _PORT_PMn10_MODE_OUTPUT | _PORT_PMn9_MODE_OUTPUT | 
                _PORT_PMn8_MODE_UNUSED | _PORT_PMn7_MODE_UNUSED | _PORT_PMn6_MODE_UNUSED | _PORT_PMn5_MODE_INPUT | 
                _PORT_PMn4_MODE_UNUSED | _PORT_PMn3_MODE_UNUSED | _PORT_PMn2_MODE_UNUSED | _PORT_PMn1_MODE_UNUSED | 
                _PORT_PMn0_MODE_UNUSED;
    PORT.PIBC11 = _PORT_PIBCn5_INPUT_BUFFER_ENABLE;
    /* Port18 setting */
    PORT.PU18 = _PORT_PUn3_PULLUP_ON | _PORT_PUn2_PULLUP_ON | _PORT_PUn1_PULLUP_ON | _PORT_PUn0_PULLUP_ON;
    PORT.PIS18 = _PORT_PIS18_DEFAULT_VALUE | _PORT_PISn3_TYPE_SHMT4 | _PORT_PISn2_TYPE_SHMT4 | 
                 _PORT_PISn1_TYPE_SHMT4 | _PORT_PISn0_TYPE_SHMT4;
    PORT.PM18 = _PORT_PM18_DEFAULT_VALUE | _PORT_PMn3_MODE_INPUT | _PORT_PMn2_MODE_INPUT | _PORT_PMn1_MODE_INPUT | 
                _PORT_PMn0_MODE_INPUT;
    PORT.PIBC18 = _PORT_PIBCn3_INPUT_BUFFER_ENABLE | _PORT_PIBCn2_INPUT_BUFFER_ENABLE | 
                  _PORT_PIBCn1_INPUT_BUFFER_ENABLE | _PORT_PIBCn0_INPUT_BUFFER_ENABLE;
    /* Port20 setting */
    PORT.PU20 = _PORT_PUn5_PULLUP_OFF | _PORT_PUn4_PULLUP_OFF;
    PORT.PD20 = _PORT_PDn5_PULLDOWN_OFF | _PORT_PDn4_PULLDOWN_OFF;
    PORT.PIS20 = _PORT_PIS20_DEFAULT_VALUE | _PORT_PISn5_TYPE_SHMT4 | _PORT_PISn4_TYPE_SHMT4;
    PORT.PM20 = _PORT_PM20_DEFAULT_VALUE | _PORT_PMn5_MODE_INPUT | _PORT_PMn4_MODE_INPUT;
    PORT.PIBC20 = _PORT_PIBCn5_INPUT_BUFFER_ENABLE | _PORT_PIBCn4_INPUT_BUFFER_ENABLE;
    /* Synchronization processing */
    g_cg_sync_read = PORT.PM0;
    __syncp();
}

/* Start user code for adding. Do not edit comment generated here */
/* End user code. Do not edit comment generated here */
